spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_1
    username: root
    password: root1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

